GET http://localhost:8000/api/skills/

###

POST http://localhost:8000/api/skills/
Content-Type: application/json

{
    "name": "Oracle"
}


###

GET http://localhost:8000/api/skills/2

###

DELETE http://localhost:8000/api/skills/10/

###

PUT http://localhost:8000/api/skills/6/
Content-Type: application/json

{
    "name": "PHP"
}